In [1]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

tf.get_default_graph().get_operations()

Instructions for updating:
non-resource variables are not supported in the long term


[]

In [2]:
a = tf.constant(7.0 , name = "data1") # const는 상수형태
b = tf.constant(3.0 , name = "data2")
c = tf.constant(2.0 , name = "data3")

tf.get_default_graph().get_operations()

[<tf.Operation 'data1' type=Const>,
 <tf.Operation 'data2' type=Const>,
 <tf.Operation 'data3' type=Const>]

In [5]:
print(a)
print()
print(a.op)

Tensor("data1:0", shape=(), dtype=float32)

name: "data1"
op: "Const"
attr {
  key: "dtype"
  value {
    type: DT_FLOAT
  }
}
attr {
  key: "value"
  value {
    tensor {
      dtype: DT_FLOAT
      tensor_shape {
      }
      float_val: 7.0
    }
  }
}



In [7]:
print(a.op.outputs) # a의 입력값을 확인
print(a is a.op.outputs[0]) # 텐서 a 와 a의 operation의 출력이 같은지 확인
print(a.op.node_def.attr["value"].tensor.float_val[0]) 
# a의 operation protocol 버퍼에서 출력값을 확인해 볼 수 있음 

[<tf.Tensor 'data1:0' shape=() dtype=float32>]
True
7.0


In [8]:
v = a * b / c

tf.get_default_graph().get_operations()

[<tf.Operation 'data1' type=Const>,
 <tf.Operation 'data2' type=Const>,
 <tf.Operation 'data3' type=Const>,
 <tf.Operation 'mul' type=Mul>,
 <tf.Operation 'truediv' type=RealDiv>]

In [10]:
print("v.op.outputs = " , v.op.outputs) 
print(v.op.outputs[0] is v) 

v.op.outputs =  [<tf.Tensor 'truediv:0' shape=() dtype=float32>]
True


In [11]:
print(v.op)

name: "truediv"
op: "RealDiv"
input: "mul"
input: "data3"
attr {
  key: "T"
  value {
    type: DT_FLOAT
  }
}



In [12]:
print(v.op.inputs[0])
print(v.op.inputs[1])

Tensor("mul:0", shape=(), dtype=float32)
Tensor("data3:0", shape=(), dtype=float32)


In [15]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(sess.run(v))

10.5


텐서는 내용을 변경할수는 없음 새로운 텐서를 만드는것만 가능 
텐서는 Rank , shape , Type 3가지 구성요소를 가지고 있음 

랭크가 0이면 스칼라 / 1이라면 벡터 / 2라면 행렬 / 3이상이라면 n - Tensor 또는 
n차원 텐서 

tf.constant = 상수 , 상수형은 말 그대로 상수를 저장하는 데이터 형 

tf.variable  조건에 따라 값을 바꿔야 하는 경우 사용하는 자료형 
변수는 반드시 명시적으로 초기화 해야함 

tf.placeholder :먼저 만들고 값을 나중에 지정해주는 자료형 
값을 나중에 정의하는 특이한 자료형 

In [17]:
a = tf.constant(5)
b = tf.constant(2)
c = tf.constant(3)
d = tf.multiply(a , b)
e = tf.add(c,d)
f = tf.subtract(d ,e)

print(a)
print(b)
print(c)
print(d)
print(e)
print(f)

Tensor("Const_3:0", shape=(), dtype=int32)
Tensor("Const_4:0", shape=(), dtype=int32)
Tensor("Const_5:0", shape=(), dtype=int32)
Tensor("Mul_2:0", shape=(), dtype=int32)
Tensor("Add_1:0", shape=(), dtype=int32)
Tensor("Sub_1:0", shape=(), dtype=int32)


In [19]:
sess = tf.Session()
outs = sess.run(f)
sess.close()
print("outs = " , outs)

outs =  -3


In [20]:
hello = tf.constant("Hello , Tensorflow!")
sess = tf.Session()
print(sess.run(hello))
sess.close()

b'Hello , Tensorflow!'


In [22]:
input_data = [1,2,3,4,5]
x = tf.placeholder(dtype = tf.float32)
y = x  * 2

sess = tf.Session()
result = sess.run(y , feed_dict = {x:input_data})
sess.close()

print(result)

[ 2.  4.  6.  8. 10.]


In [25]:
p_holder1 = tf.placeholder(dtype = tf.float32)
p_holder2 = tf.placeholder(dtype = tf.float32)
p_holder3 = tf.placeholder(dtype = tf.float32)

val1 = 5
val2 = 10
val3 = 3

ret_val = p_holder1 * p_holder2 + p_holder3

sess = tf.Session()
feed_dict_data = {p_holder1 : val1 , p_holder2 : val2 , p_holder3 : val3}
result = sess.run(ret_val , feed_dict = feed_dict_data)
sess.close()
print(result)

53.0


In [26]:
I = tf.placeholder(tf.float32 , [2,4])
i = [[1,2,3,4] , [5,6,7,8]]

W = tf.placeholder(tf.float32 , [4,2])
w = [[1,1] , [2,2] , [3,3] , [4,4]]

# input 데이터와 weight를 행렬곱 수행 
m_cal = tf.matmul(I , W)

sess = tf.Session()

print(sess.run(m_cal , feed_dict = {I:i , W:w}))

sess.close()

[[30. 30.]
 [70. 70.]]


In [28]:
I = tf.Variable([[1,2,3,4] , [5,6,7,8]] , tf.float32)
W = tf.Variable([[1,1] , [2,2] , [3,3] , [4,4]] , tf.float32)

m_cal = tf.matmul(I , W)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

print(sess.run(m_cal))

sess.close()

[[30 30]
 [70 70]]


In [33]:
input_data = [1,2,3,4,5]
x = tf.placeholder(dtype = tf.float32)
W = tf.Variable([2] , dtype = tf.float32) # <= 값을 미리 지정해줘야 하는데 지정을 하지않음
y = W * x

sess = tf.Session()

init = tf.global_variables_initializer()
sess.run(init)
result = sess.run(y , feed_dict={x : input_data })
print(result)

[ 2.  4.  6.  8. 10.]


In [34]:
x = tf.Variable(5 , dtype = tf.int32)
print(x)

z = tf.assign(x , 7)
sess = tf.Session()
sess.run(z)
y = sess.run(x)
print(y)
sess.close()

<tf.Variable 'Variable_5:0' shape=() dtype=int32_ref>
7


In [38]:
x = tf.Variable(tf.zeros((2,2)) , dtype = tf.float32)
print(x)

y = tf.Variable([[1,2] , [3,4]] , dtype = tf.float32)
x = tf.assign(x , y) 
sess = tf.Session()
z = tf.global_variables_initializer()
sess.run(z)
k = sess.run(x)
sess.close()

print(k)

<tf.Variable 'Variable_9:0' shape=(2, 2) dtype=float32_ref>
[[1. 2.]
 [3. 4.]]


In [46]:
mat_img = [1,2,3,4,5]
label = [10,20,30,40,50]
ph_img = tf.placeholder(dtype = tf.float32)
ph_lb = tf.placeholder(dtype = tf.float32)

ret_tensor = ph_img + ph_lb

sess = tf.Session()

result = sess.run(ret_tensor , feed_dict={ph_img : mat_img , ph_lb : label} )
sess.close()
print(result)

[11. 22. 33. 44. 55.]


In [47]:
input_data = [[1,2,3] , [1,2,3] , [2,3,4]]
x = tf.placeholder(dtype = tf.float32 , shape = [None , 3])
w = tf.Variable([[2.] , [2.] , [2.]] , dtype = tf.float32)
y = tf.matmul(x , w)
sess = tf.Session()
init = tf.global_variables_initializer()
sess.run(init)
result = sess.run(y , feed_dict = {x : input_data})
sess.close()
print(result)

[[12.]
 [12.]
 [18.]]


In [48]:
input_data = [[1,1,1] , [2,2,2]]
x = tf.placeholder(dtype = tf.float32 , shape = [2 , 3])
w = tf.Variable([[2.] , [2.] , [2.]] , dtype = tf.float32)
b = tf.Variable([4] , dtype = tf.float32)
y = tf.matmul(x , w) + b
print(x.get_shape())
sess = tf.Session()
init = tf.global_variables_initializer()
sess.run(init)
result = sess.run(y , feed_dict = {x : input_data})
sess.close()
print(result)

(2, 3)
[[10.]
 [16.]]


In [49]:
x = tf.constant([[1.0 , 2.0 , 3.0]])
w = tf.constant([[2.0] , [2.0] , [2.0] ])
y = tf.matmul(x , w)
print(x.get_shape())
print(w.get_shape())
print(y.get_shape())
print(y)
sess = tf.Session()
init = tf.global_variables_initializer()
sess.run(init)
result = sess.run(y)

sess.close()
print(result)

(1, 3)
(3, 1)
(1, 1)
Tensor("MatMul_5:0", shape=(1, 1), dtype=float32)
[[12.]]
