## 로지스틱 회귀

In [14]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
import numpy as np

# 학습할 데이터
data = [[2,0] , [4,0] , [6,0]  ,[8,1] , [10,1] , [12,1] , [14,1]]

# 데이터 분리
x_data = [x_row[0] for x_row in data]
y_data = [y_row[1] for y_row in data]

# 변수 설정 
a = tf.Variable(tf.random_normal([1] , dtype = tf.float64 , seed = 0))
b = tf.Variable(tf.random_normal([1] , dtype = tf.float64 , seed = 0))

# 로지스틱 회귀 식 (최소제곱법 대신 사용하는것 그렇다고 로지스틱 회귀에서도 최소제곱법이 사용가능한것이 아님)
# np.e 의 e는 수학에서 파이같은 정해져 있는 수 
y = 1/(1 + np.e ** - (a * x_data + b))

# 최소제곱법과 비슷하지만 log를 사용
loss = -tf.reduce_mean(np.array(y_data) * tf.log(y) + (1 - np.array(y_data)) * tf.log(1 - y))

# 학습률 
learning_rate = 0.5

# 경사하강법 
gradient_decent = tf.train.GradientDescentOptimizer(learning_rate).minimize(loss)

#tensorflow 1.xx 버전이므로 Session으로 run
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for i in range(60001):
        sess.run(gradient_decent)
        if i % 10000 == 0:
            print("Epoch : %.f , loss : %.4f , 기울기 a = %.4f , y 절편 = %.4f" %
                 (i , sess.run(loss) , sess.run(a) , sess.run(b)))
    calc_a = sess.run(a)
    calc_b = sess.run(b)
    
# def new_data(x):
#     return 1/(1 + np.e ** - (calc_a * x + calc_b))

# print(new_data(5))
# print(new_data(7))
# print(new_data(13))

dx = [5,7,13]
calc_y = 1/(1 + np.e ** - (calc_a * dx + calc_b))
print(calc_y)

#     new_x_data = 5
#     y_test = 1/(1 + np.e ** - (a * new_x_data + b))
#     print(sess.run(y_test))
#     print(sess.run(y_test[0]))
    
#     new_x_data = 7
#     y_test = 1/(1 + np.e ** - (a * new_x_data + b))
#     print(sess.run(y_test))
#     print(sess.run(y_test[0]))
          
#     new_x_data = 13
#     y_test = 1/(1 + np.e ** - (a * new_x_data + b))
#     print(sess.run(y_test))
#     print(sess.run(y_test[0]))
#     print(y_test)

Epoch : 0 , loss : 4.0817 , 기울기 a = 2.4706 , y 절편 = -0.3620
Epoch : 10000 , loss : 0.0096 , 기울기 a = 3.3918 , y 절편 = -23.5969
Epoch : 20000 , loss : 0.0049 , 기울기 a = 4.0594 , y 절편 = -28.2724
Epoch : 30000 , loss : 0.0033 , 기울기 a = 4.4590 , y 절편 = -31.0705
Epoch : 40000 , loss : 0.0025 , 기울기 a = 4.7447 , y 절편 = -33.0707
Epoch : 50000 , loss : 0.0020 , 기울기 a = 4.9671 , y 절편 = -34.6275
Epoch : 60000 , loss : 0.0017 , 기울기 a = 5.1491 , y 절편 = -35.9020
[3.88235157e-05 5.35379864e-01 1.00000000e+00]


In [32]:
input_data = [1,2,3,4,5]

x = tf.placeholder(dtype = tf.float32)
y = x * 2

sess = tf.Session()
result = sess.run(y , feed_dict = {x : input_data})
sess.close()

print(result)

[ 2.  4.  6.  8. 10.]


In [35]:
# 행렬연산식 
input_data = [[1,1,1] , [2,2,2]]
x = tf.placeholder(dtype = tf.float32 , shape = [2,3])
w = tf.Variable([[2] , [2] , [2]] , dtype = tf.float32)
b = tf.Variable([4] , dtype = tf.float32)
y = tf.matmul(x , w) + b
print(x.get_shape)
sess = tf.Session()
init = tf.global_variables_initializer()
sess.run(init)
result = sess.run( y , feed_dict = {x: input_data})

print(result)

<bound method Tensor.get_shape of <tf.Tensor 'Placeholder_3:0' shape=(2, 3) dtype=float32>>
[[10.]
 [16.]]


In [43]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
import numpy as np

# 실행할 때마다 같은 결과를 출력하기 위한 seed 값 설정
seed = 0
np.random.seed(seed)
tf.set_random_seed(seed)

# x , y의 데이터 값
x_data = np.array([[2,3] , [4,3] , [6,4] , [8,6] , [10,7] ,[12,8] , [14,9]])
y_data = np.array([0,0,0,1,1,1,1]).reshape(7,1)

# 입력 값을 플레이스 홀더에 저장
X = tf.placeholder(tf.float64 , shape = [None , 2])
Y = tf.placeholder(tf.float64 , shape = [None , 1])


# 기울기 a와 바이어스 b의 값을 임의로 정함 a는 [2,1]의 형태를 가짐 a1 , a2
a = tf.Variable(tf.random_uniform([2,1] , dtype = tf.float64))

# [2,1] 의미 : 들어오는 값 2개 , 나가는 값 1개
b = tf.Variable(tf.random_uniform([1] , dtype = tf.float64))

# y 시그모이드 함수의 방정식을 세움
y = tf.sigmoid(tf.matmul(X , a) + b)

# 오차를 구하는 함수
loss = -tf.reduce_mean(Y * tf.log(y) + (1 - Y ) * tf.log(1 - y))

# 학습률 값
learning_rate = 0.1

# 오차를 최소로 하는 값 찾기 
gradient_decent = tf.train.GradientDescentOptimizer(learning_rate).minimize(loss)

# predicted y가 0.5보다 작으면 1 
predicted = tf.cast(y > 0.5 , dtype = tf.float64)

# bool연산 True , False를 판단 , predicted , y 가 같으면 1 , 같지않으면 0 
# predicted는 0 , 1로 이루어져 있기때문에 판단가능 
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted , Y) , dtype = tf.float64))

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    for i in range(3001):
        a_ , b_ , loss_ , _ = sess.run([a, b , loss , gradient_decent] , feed_dict= {X : x_data , Y : y_data })
        if (i + 1) % 300 == 0:
 print("Epoch: %f , RMSE = %.04f , 기울기 a = %.4f , y절편 b = %.4f" %(step , sess.run(rmse) , sess.run(a) , sess.run(b)))            
    print("predicted = " , sess.run(predicted , feed_dict = {X : x_data}))
    p_val , h_val = sess.run([predicted ,y] , feed_dict = {X : [[1,5] , [10,5] , [4,5]]})
    print("check predicted = " , p_val)
    print("check hypothesis = " , h_val)
    
    h ,c , a = sess.run([y , predicted , accuracy] , feed_dict = {X : x_data , Y : y_data})
    print("\n/Hypothesis : " , h , "\nCorrect (Y): " , c , "\nAccuracy : " , a)

step = 300 , a1 = 0.7858 ,a2 = -0.5046, b = -2.4734 , loss = 0.2641
step = 600 , a1 = 0.7962 ,a2 = -0.2490, b = -3.9345 , loss = 0.1895
step = 900 , a1 = 0.7133 ,a2 = 0.0675, b = -4.9915 , loss = 0.1485
step = 1200 , a1 = 0.6147 ,a2 = 0.3660, b = -5.8283 , loss = 0.1217
step = 1500 , a1 = 0.5194 ,a2 = 0.6334, b = -6.5228 , loss = 0.1029
step = 1800 , a1 = 0.4327 ,a2 = 0.8701, b = -7.1169 , loss = 0.0890
step = 2100 , a1 = 0.3552 ,a2 = 1.0795, b = -7.6364 , loss = 0.0783
step = 2400 , a1 = 0.2865 ,a2 = 1.2658, b = -8.0980 , loss = 0.0699
step = 2700 , a1 = 0.2254 ,a2 = 1.4325, b = -8.5134 , loss = 0.0631
step = 3000 , a1 = 0.1710 ,a2 = 1.5826, b = -8.8911 , loss = 0.0574
predicted =  [[0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]]
check predicted =  [[0.]
 [1.]
 [0.]]
check hypothesis =  [[0.30876517]
 [0.67506926]
 [0.42713956]]

/Hypothesis :  [[0.02185232]
 [0.03047867]
 [0.17725235]
 [0.87790586]
 [0.98010999]
 [0.9970475 ]
 [0.99956808]] 
Correct (Y):  [[0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.

In [21]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
import numpy as np

data = [[2,0] , [4,0] , [6,0]  ,[8,1] , [10,1] , [12,1] , [14,1]]

x_data = [x_row[0] for x_row in data]
y_data = [y_row[1] for y_row in data]

a = tf.Variable(0 , dtype = tf.float64)
b = tf.Variable(0 , dtype = tf.float64)

y = a * x_data + b

rmse = tf.sqrt(tf.reduce_mean(tf.square(y - y_data)))

learning_rate = 0.01

gradient_decent = tf.train.GradientDescentOptimizer(learning_rate).minimize(rmse)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for i in range(60001):
        sess.run(gradient_decent)
        if i % 1000 == 0:
            print("Epoch: %f , RMSE = %.04f , 기울기 a = %.4f , y절편 b = %.4f" %(i , sess.run(rmse) , sess.run(a) , sess.run(b)))

Epoch: 0.000000 , RMSE = 0.2841 , 기울기 a = 0.0832 , y절편 b = 0.0076
Epoch: 1000.000000 , RMSE = 0.4040 , 기울기 a = 0.1423 , y절편 b = -0.2800
Epoch: 2000.000000 , RMSE = 0.4040 , 기울기 a = 0.1425 , y절편 b = -0.2822
Epoch: 3000.000000 , RMSE = 0.4040 , 기울기 a = 0.1425 , y절편 b = -0.2822
Epoch: 4000.000000 , RMSE = 0.4040 , 기울기 a = 0.1425 , y절편 b = -0.2822
Epoch: 5000.000000 , RMSE = 0.4040 , 기울기 a = 0.1425 , y절편 b = -0.2822
Epoch: 6000.000000 , RMSE = 0.4040 , 기울기 a = 0.1425 , y절편 b = -0.2822
Epoch: 7000.000000 , RMSE = 0.4040 , 기울기 a = 0.1425 , y절편 b = -0.2822
Epoch: 8000.000000 , RMSE = 0.4040 , 기울기 a = 0.1425 , y절편 b = -0.2822
Epoch: 9000.000000 , RMSE = 0.4040 , 기울기 a = 0.1425 , y절편 b = -0.2822
Epoch: 10000.000000 , RMSE = 0.4040 , 기울기 a = 0.1425 , y절편 b = -0.2822
Epoch: 11000.000000 , RMSE = 0.4040 , 기울기 a = 0.1425 , y절편 b = -0.2822
Epoch: 12000.000000 , RMSE = 0.4040 , 기울기 a = 0.1425 , y절편 b = -0.2822
Epoch: 13000.000000 , RMSE = 0.4040 , 기울기 a = 0.1425 , y절편 b = -0.2822
Epoch: 14000.000000 