In [16]:
import tensorflow as tf
import numpy as np

In [42]:

data = np.loadtxt("/Users/panhong/Desktop/coding_study/Likelion_KDT/Jupyter_notebook/Blood_fat.csv" , delimiter = ",")

x1 = [x_row[0] for x_row in data]
x2 = [y_row[1] for y_row in data]
y_data = [i[2] for i in data]

a1 = tf.Variable(tf.random.uniform([1] , 0 , 10 , dtype = tf.float64 , seed = 0))
a2 = tf.Variable(tf.random.uniform([1] , 0 , 10 , dtype = tf.float64 , seed = 0))
b = tf.Variable(tf.random.uniform([1] , 0 , 100 , dtype = tf.float64 , seed = 0))

def hyper(a1 , a2 , b):
    return a1 * x1 + a2 * x2 + b
    
def costFunc():
    return tf.sqrt(tf.reduce_mean(tf.square(hyper(a1 , a2 , b) - y_data)))

def cost(a1 , a2 , b):
    return tf.sqrt(tf.reduce_mean(tf.square(hyper(a1 , a2 , b) - y_data)))

opt = tf.keras.optimizers.SGD(learning_rate = 0.01)

for i in range(6000):
    opt.minimize(costFunc , var_list = [a1 , a2 , b])
    if i % 100 == 0:
        print(i , f"{cost(a1 , a2 , b)} , {a1.numpy()} , {a2.numpy()} , {b.numpy()}")
print()
da1 = a1.numpy()
da2 = a2.numpy()
db = b.numpy()

for i in range(25):
    print((da1 * x1[i]) + (da2 * x2[i]) + db)
    


0 380.07764657355534 , [7.33606836] , [2.44717428] , [79.35068005]
100 41.90734613189912 , [0.70835435] , [4.67599465] , [79.28532771]
200 41.38174163713514 , [0.42051548] , [5.17889277] , [79.28360172]
300 41.37991528131175 , [0.40360861] , [5.20845238] , [79.28266274]
400 41.37990827314593 , [0.40263148] , [5.21018149] , [79.28177073]
500 41.3799074623609 , [0.40258398] , [5.21028646] , [79.28088202]
600 41.3799066737573 , [0.40259073] , [5.21029664] , [79.27999409]
700 41.3799058863037 , [0.40260063] , [5.21030128] , [79.27910677]
800 41.37990509992702 , [0.40261072] , [5.2103056] , [79.27822006]
900 41.379904314625534 , [0.40262081] , [5.2103099] , [79.27733395]
1000 41.37990353039778 , [0.40263089] , [5.2103142] , [79.27644845]
1100 41.37990274724227 , [0.40264096] , [5.21031849] , [79.27556355]
1200 41.379901965157565 , [0.40265103] , [5.21032278] , [79.27467927]
1300 41.37990118414218 , [0.40266109] , [5.21032707] , [79.27379558]
1400 41.37990040419465 , [0.40267114] , [5.210331

In [52]:
import tensorflow as tf 
import numpy as np

data = [[2,0] , [4,0] , [6,0]  ,[8,1] , [10,1] , [12,1] , [14,1]]

x_data = [x_row[0] for x_row in data]
y_data = [y_row[1] for y_row in data]

a = tf.Variable(tf.random.normal([1] ,  dtype = tf.float64 , seed = 0))
b = tf.Variable(tf.random.normal([1] ,  dtype = tf.float64 , seed = 0))

def hyoper(a , b):
    return 1/(1 + np.e **  - (a * x_data + b))

# 최솟값 찾기 구문 
def costFunc():
    return - tf.reduce_mean(np.array(y_data) * tf.math.log(hyoper(a , b)) + (1 - np.array(y_data)) * tf.math.log(1 - hyoper(a , b)))

# 코드는 같아보이지만 a, b값을 지속적으로 업데이트해주는 함수
def cost(a , b):
    return - tf.reduce_mean(np.array(y_data) * tf.math.log(hyoper(a , b)) + (1 - np.array(y_data)) * tf.math.log(1 - hyoper(a , b)))
    
opt = tf.keras.optimizers.SGD(learning_rate = 0.5)

for i in range(60001):
    opt.minimize(costFunc , var_list = [a , b])
    if i % 10000 == 0:
        print(i , f"{cost(a,b)} , {a.numpy()} , {b.numpy()}")

new_x_data = 5
y_test = 1 / (1 + np.e ** - (a * new_x_data + b))
print(y_test.numpy())
print("%.40f"% float(y_test.numpy()))

new_x_data = 7
y_test = 1 / (1 + np.e ** - (a * new_x_data + b))
print(y_test.numpy())
print("%.40f"% float(y_test.numpy()))

new_x_data = 13
y_test = 1 / (1 + np.e ** - (a * new_x_data + b))
print(y_test.numpy())
print("%.40f"% float(y_test.numpy()))


0 0.7046493767506787 , [0.00174515] , [-0.17272612]
10000 0.009569373569716964 , [3.39108349] , [-23.59155453]
20000 0.00494164382272449 , [4.05901793] , [-28.26967013]
30000 0.0033220435840227982 , [4.45874603] , [-31.06862007]
40000 0.002499734584140515 , [4.74449293] , [-33.06927249]
50000 0.002002905674782267 , [4.96690333] , [-34.62639856]
60000 0.0016704465416737054 , [5.14896671] , [-35.90101047]
[3.8833947e-05]
0.0000388339469500579307021173591785156987
[0.53537989]
0.5353798918426254660474228330713231116533
[1.]
0.9999999999999666933092612453037872910500


리스트는 파이썬에 존재하는 연속된 자료형 
배열은 넘파이 모듈에서 사용하는 연속된 자료형 
벡터연산 = 배열 가능 , 리스트 불가능 

ex) [1,2,3] + [4,5,6]
결과는 리스트는 1,2,3,4,5,6 
     배열은 [5,7,9]
     
a.reshape(데이터는 같지만 배열의 차원을 바꾸어주는 함수)

numpy는 리스트와 비슷하지만 배열내에는 , 가 없다.

In [54]:
a = np.arange(12) # 배열생성
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [56]:
a = a.reshape(3,4) # 4개의 요소를 가진 2차원 배열이 3개
a 

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [57]:
a.ravel() # 다차원의 a를 1차원으로 다시 변경 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [58]:
import numpy as np
a = np.array([1,2,3,4,5])
b = a 
c = a.copy()
b[0] = 99
print(a)
print(b)
print(c)

[99  2  3  4  5]
[99  2  3  4  5]
[1 2 3 4 5]


In [60]:
a = [1,2,3,4,5]
b = np.array(a)
c = np.array([1,3,5])
print(a * 2)
print(b * 2)
print(c + 3)

# numpy는 list와 다르게 수학기호를 사용한다면 각각의 원소로 계산하여 반환합니다.
# list의 경우 *기호 사용시 해당 배열을 이어붙이지만 numpy의 경우 연산을 실행 
# Tip : numpy를 사용할 경우 list , comprehension을 사용하지 않아도
# 원소의 값을 연산할 수 있습니다.

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[ 2  4  6  8 10]
[4 6 8]


In [62]:
a = np.ones((2,2) , dtype = int)
b = [1,2,3,4,5]
c = np.ones_like(b , dtype = int)
print(a)
print(b)
print(c)

[[1 1]
 [1 1]]
[1, 2, 3, 4, 5]
[1 1 1 1 1]


In [64]:
a = np.identity(4 , dtype = int)
b = np.eye(4 , 4, k = 1,dtype = int)
print(a)
print(b)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
[[0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]
 [0 0 0 0]]


텐서플로에 3가지 자료형 = constant(상수형) , variable(변수형) , placeholder(초기값이 없는 자료형 진행중에 값을 할당)

dtype , shape , name = placeholder에 입력되는 자료형들

placeholder은 텐서플로의 1 버전에서만 사용가능 
feed_dict = {}로 placeholder에 값을 입력해주고 
이 과정을 피딩이라고 한다.